"""Global configuration parameters."""

from __future__ import annotations

from hahomematic.const import (
    DEFAULT_CONNECTION_CHECKER_INTERVAL,
    DEFAULT_JSON_SESSION_AGE,
    DEFAULT_PING_PONG_MISMATCH_COUNT,
    DEFAULT_PING_PONG_MISMATCH_COUNT_TTL,
    DEFAULT_RECONNECT_WAIT,
    DEFAULT_TIMEOUT,
)

CALLBACK_WARN_INTERVAL = DEFAULT_CONNECTION_CHECKER_INTERVAL * 40
CONNECTION_CHECKER_INTERVAL = DEFAULT_CONNECTION_CHECKER_INTERVAL
JSON_SESSION_AGE = DEFAULT_JSON_SESSION_AGE
PING_PONG_MISMATCH_COUNT = DEFAULT_PING_PONG_MISMATCH_COUNT
PING_PONG_MISMATCH_COUNT_TTL = DEFAULT_PING_PONG_MISMATCH_COUNT_TTL
RECONNECT_WAIT = DEFAULT_RECONNECT_WAIT
TIMEOUT = DEFAULT_TIMEOUT
