"""
Global configuration parameters.
"""

from hahomematic.const import DEFAULT_INTERFACE_ID, DEFAULT_TIMEOUT, DEFAULT_INIT_TIMEOUT

INTERFACE_ID = DEFAULT_INTERFACE_ID
TIMEOUT = DEFAULT_TIMEOUT
INIT_TIMEOUT = DEFAULT_INIT_TIMEOUT
FILE_DEVICES = None
FILE_PARAMSETS = None
FILE_NAMES = None

SYSTEMCALLBACK = None
EVENTCALLBACK = None
